name: Delete v1.0 and v1.1 releases

on:
  schedule:
    - cron: '0 0 5 8 *'

jobs:
  delete-releases:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const tags = ['v1.0', 'v1.1'];
            for (const tag of tags) {
              try {
                const release = await github.rest.repos.getReleaseByTag({ owner, repo, tag });
                await github.rest.repos.deleteRelease({ owner, repo, release_id: release.data.id });
                console.log(`Release '${tag}' gelöscht.`);
              } catch (err) {
                console.log(`Release '${tag}' nicht gefunden: ${err.message}`);
              }

              try {
                await github.rest.git.deleteRef({ owner, repo, ref: `tags/${tag}` });
                console.log(`Tag '${tag}' gelöscht.`);
              } catch (err) {
                console.log(`Tag '${tag}' nicht gefunden: ${err.message}`);
              }
            }
